name = "wind-force-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "FORECAST_CACHE"
id = "e767f9f63ec641e197973ea9cec58e1b"

[[routes]]
pattern = "api-wind-force.kayakshaver.com/*"
zone_name = "kayakshaver.com"

# Without routes, the Worker deploys to:
#   https://wind-force-proxy.<your-account>.workers.dev
